#include <config/secrets.h>
#include "environment.h"

/**
 * @file
 * @brief       Application Secrets Setup Default-Implementation
 *      
 *              This file holds default secrets and serves as a reference for the 
 *              implementor. In order to create your own secrets, see
 *              instructions in `README.md` of this folder.
 * 
 * @warning     This is a template. DO NOT EDIT THIS FILE! (see description above)
 * 
 * @author      Ueli Niederer, ueli.niederer@niederer-engineering.ch         
 * @copyright   Copyright (c) 2021 by Niederer Engineering GmbH
 */

 /**
  * @brief WiFi SSID to connect to
  */
ENV_WEAK const char *SECRET_WIFI_SSID = "MyNetwork";
 
 /**
  * @brief WiFi password (PSK) for the SSID to connect to
  */
ENV_WEAK const char *SECRET_WIFI_PASSWORD = "secretPassword";
